services:
  wasm-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Mount volumes to allow live reloading for development
    volumes:
      - ./wasmJsDist:/app:ro