name: Publish to Maven Central
on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  publish:
    name: Release build and publish
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Will publish version: $VERSION"

      - name: Decode GPG key
        run: |
          echo "${{ secrets.GPG_KEY_CONTENTS }}" | base64 --decode > ${{ github.workspace }}/secring.gpg

      - name: Build & Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ github.workspace }}/secring.gpg
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          ./gradlew publishAllPublicationsToSonatypeRepository -Pversion=$VERSION